#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace send_working_day
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BioStar")]
	public partial class WorkingDayDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_EVENT_LOG(TB_EVENT_LOG instance);
    partial void UpdateTB_EVENT_LOG(TB_EVENT_LOG instance);
    partial void DeleteTB_EVENT_LOG(TB_EVENT_LOG instance);
    partial void InsertTB_USER(TB_USER instance);
    partial void UpdateTB_USER(TB_USER instance);
    partial void DeleteTB_USER(TB_USER instance);
    partial void InsertTB_READER(TB_READER instance);
    partial void UpdateTB_READER(TB_READER instance);
    partial void DeleteTB_READER(TB_READER instance);
    #endregion
		
		public WorkingDayDBDataContext() : 
				base(global::send_working_day.Properties.Settings.Default.BioStarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WorkingDayDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkingDayDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkingDayDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WorkingDayDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_EVENT_LOG> TB_EVENT_LOGs
		{
			get
			{
				return this.GetTable<TB_EVENT_LOG>();
			}
		}
		
		public System.Data.Linq.Table<TB_USER> TB_USERs
		{
			get
			{
				return this.GetTable<TB_USER>();
			}
		}
		
		public System.Data.Linq.Table<TB_READER> TB_READERs
		{
			get
			{
				return this.GetTable<TB_READER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_EVENT_LOG")]
	public partial class TB_EVENT_LOG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nEventLogIdn;
		
		private int _nDateTime;
		
		private int _nReaderIdn;
		
		private int _nEventIdn;
		
		private int _nUserID;
		
		private short _nIsLog;
		
		private short _nTNAEvent;
		
		private short _nIsUseTA;
		
		private short _nType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnEventLogIdnChanging(int value);
    partial void OnnEventLogIdnChanged();
    partial void OnnDateTimeChanging(int value);
    partial void OnnDateTimeChanged();
    partial void OnnReaderIdnChanging(int value);
    partial void OnnReaderIdnChanged();
    partial void OnnEventIdnChanging(int value);
    partial void OnnEventIdnChanged();
    partial void OnnUserIDChanging(int value);
    partial void OnnUserIDChanged();
    partial void OnnIsLogChanging(short value);
    partial void OnnIsLogChanged();
    partial void OnnTNAEventChanging(short value);
    partial void OnnTNAEventChanged();
    partial void OnnIsUseTAChanging(short value);
    partial void OnnIsUseTAChanged();
    partial void OnnTypeChanging(short value);
    partial void OnnTypeChanged();
    #endregion
		
		public TB_EVENT_LOG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nEventLogIdn", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int nEventLogIdn
		{
			get
			{
				return this._nEventLogIdn;
			}
			set
			{
				if ((this._nEventLogIdn != value))
				{
					this.OnnEventLogIdnChanging(value);
					this.SendPropertyChanging();
					this._nEventLogIdn = value;
					this.SendPropertyChanged("nEventLogIdn");
					this.OnnEventLogIdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nDateTime", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nDateTime
		{
			get
			{
				return this._nDateTime;
			}
			set
			{
				if ((this._nDateTime != value))
				{
					this.OnnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._nDateTime = value;
					this.SendPropertyChanged("nDateTime");
					this.OnnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nReaderIdn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nReaderIdn
		{
			get
			{
				return this._nReaderIdn;
			}
			set
			{
				if ((this._nReaderIdn != value))
				{
					this.OnnReaderIdnChanging(value);
					this.SendPropertyChanging();
					this._nReaderIdn = value;
					this.SendPropertyChanged("nReaderIdn");
					this.OnnReaderIdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nEventIdn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nEventIdn
		{
			get
			{
				return this._nEventIdn;
			}
			set
			{
				if ((this._nEventIdn != value))
				{
					this.OnnEventIdnChanging(value);
					this.SendPropertyChanging();
					this._nEventIdn = value;
					this.SendPropertyChanged("nEventIdn");
					this.OnnEventIdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nUserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nUserID
		{
			get
			{
				return this._nUserID;
			}
			set
			{
				if ((this._nUserID != value))
				{
					this.OnnUserIDChanging(value);
					this.SendPropertyChanging();
					this._nUserID = value;
					this.SendPropertyChanged("nUserID");
					this.OnnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIsLog", DbType="SmallInt NOT NULL")]
		public short nIsLog
		{
			get
			{
				return this._nIsLog;
			}
			set
			{
				if ((this._nIsLog != value))
				{
					this.OnnIsLogChanging(value);
					this.SendPropertyChanging();
					this._nIsLog = value;
					this.SendPropertyChanged("nIsLog");
					this.OnnIsLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nTNAEvent", DbType="SmallInt NOT NULL")]
		public short nTNAEvent
		{
			get
			{
				return this._nTNAEvent;
			}
			set
			{
				if ((this._nTNAEvent != value))
				{
					this.OnnTNAEventChanging(value);
					this.SendPropertyChanging();
					this._nTNAEvent = value;
					this.SendPropertyChanged("nTNAEvent");
					this.OnnTNAEventChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nIsUseTA", DbType="SmallInt NOT NULL")]
		public short nIsUseTA
		{
			get
			{
				return this._nIsUseTA;
			}
			set
			{
				if ((this._nIsUseTA != value))
				{
					this.OnnIsUseTAChanging(value);
					this.SendPropertyChanging();
					this._nIsUseTA = value;
					this.SendPropertyChanged("nIsUseTA");
					this.OnnIsUseTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nType", DbType="SmallInt NOT NULL")]
		public short nType
		{
			get
			{
				return this._nType;
			}
			set
			{
				if ((this._nType != value))
				{
					this.OnnTypeChanging(value);
					this.SendPropertyChanging();
					this._nType = value;
					this.SendPropertyChanged("nType");
					this.OnnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_USER")]
	public partial class TB_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nUserIdn;
		
		private string _sUserName;
		
		private int _nDepartmentIdn;
		
		private string _sTelNumber;
		
		private string _sEmail;
		
		private string _sUserID;
		
		private string _sPassword;
		
		private System.Data.Linq.Binary _bPassword2;
		
		private int _nStartDate;
		
		private int _nEndDate;
		
		private int _nAdminLevel;
		
		private int _nAuthMode;
		
		private int _nAuthLimitCount;
		
		private int _nTimedAPB;
		
		private int _nEncryption;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnUserIdnChanging(int value);
    partial void OnnUserIdnChanged();
    partial void OnsUserNameChanging(string value);
    partial void OnsUserNameChanged();
    partial void OnnDepartmentIdnChanging(int value);
    partial void OnnDepartmentIdnChanged();
    partial void OnsTelNumberChanging(string value);
    partial void OnsTelNumberChanged();
    partial void OnsEmailChanging(string value);
    partial void OnsEmailChanged();
    partial void OnsUserIDChanging(string value);
    partial void OnsUserIDChanged();
    partial void OnsPasswordChanging(string value);
    partial void OnsPasswordChanged();
    partial void OnbPassword2Changing(System.Data.Linq.Binary value);
    partial void OnbPassword2Changed();
    partial void OnnStartDateChanging(int value);
    partial void OnnStartDateChanged();
    partial void OnnEndDateChanging(int value);
    partial void OnnEndDateChanged();
    partial void OnnAdminLevelChanging(int value);
    partial void OnnAdminLevelChanged();
    partial void OnnAuthModeChanging(int value);
    partial void OnnAuthModeChanged();
    partial void OnnAuthLimitCountChanging(int value);
    partial void OnnAuthLimitCountChanged();
    partial void OnnTimedAPBChanging(int value);
    partial void OnnTimedAPBChanged();
    partial void OnnEncryptionChanging(int value);
    partial void OnnEncryptionChanged();
    #endregion
		
		public TB_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nUserIdn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nUserIdn
		{
			get
			{
				return this._nUserIdn;
			}
			set
			{
				if ((this._nUserIdn != value))
				{
					this.OnnUserIdnChanging(value);
					this.SendPropertyChanging();
					this._nUserIdn = value;
					this.SendPropertyChanged("nUserIdn");
					this.OnnUserIdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sUserName", DbType="NVarChar(96) NOT NULL", CanBeNull=false)]
		public string sUserName
		{
			get
			{
				return this._sUserName;
			}
			set
			{
				if ((this._sUserName != value))
				{
					this.OnsUserNameChanging(value);
					this.SendPropertyChanging();
					this._sUserName = value;
					this.SendPropertyChanged("sUserName");
					this.OnsUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nDepartmentIdn", DbType="Int NOT NULL")]
		public int nDepartmentIdn
		{
			get
			{
				return this._nDepartmentIdn;
			}
			set
			{
				if ((this._nDepartmentIdn != value))
				{
					this.OnnDepartmentIdnChanging(value);
					this.SendPropertyChanging();
					this._nDepartmentIdn = value;
					this.SendPropertyChanged("nDepartmentIdn");
					this.OnnDepartmentIdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTelNumber", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string sTelNumber
		{
			get
			{
				return this._sTelNumber;
			}
			set
			{
				if ((this._sTelNumber != value))
				{
					this.OnsTelNumberChanging(value);
					this.SendPropertyChanging();
					this._sTelNumber = value;
					this.SendPropertyChanged("sTelNumber");
					this.OnsTelNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sEmail
		{
			get
			{
				return this._sEmail;
			}
			set
			{
				if ((this._sEmail != value))
				{
					this.OnsEmailChanging(value);
					this.SendPropertyChanging();
					this._sEmail = value;
					this.SendPropertyChanged("sEmail");
					this.OnsEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sUserID", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string sUserID
		{
			get
			{
				return this._sUserID;
			}
			set
			{
				if ((this._sUserID != value))
				{
					this.OnsUserIDChanging(value);
					this.SendPropertyChanging();
					this._sUserID = value;
					this.SendPropertyChanged("sUserID");
					this.OnsUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sPassword", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string sPassword
		{
			get
			{
				return this._sPassword;
			}
			set
			{
				if ((this._sPassword != value))
				{
					this.OnsPasswordChanging(value);
					this.SendPropertyChanging();
					this._sPassword = value;
					this.SendPropertyChanged("sPassword");
					this.OnsPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bPassword2", DbType="Binary(32) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary bPassword2
		{
			get
			{
				return this._bPassword2;
			}
			set
			{
				if ((this._bPassword2 != value))
				{
					this.OnbPassword2Changing(value);
					this.SendPropertyChanging();
					this._bPassword2 = value;
					this.SendPropertyChanged("bPassword2");
					this.OnbPassword2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nStartDate", DbType="Int NOT NULL")]
		public int nStartDate
		{
			get
			{
				return this._nStartDate;
			}
			set
			{
				if ((this._nStartDate != value))
				{
					this.OnnStartDateChanging(value);
					this.SendPropertyChanging();
					this._nStartDate = value;
					this.SendPropertyChanged("nStartDate");
					this.OnnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nEndDate", DbType="Int NOT NULL")]
		public int nEndDate
		{
			get
			{
				return this._nEndDate;
			}
			set
			{
				if ((this._nEndDate != value))
				{
					this.OnnEndDateChanging(value);
					this.SendPropertyChanging();
					this._nEndDate = value;
					this.SendPropertyChanged("nEndDate");
					this.OnnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nAdminLevel", DbType="Int NOT NULL")]
		public int nAdminLevel
		{
			get
			{
				return this._nAdminLevel;
			}
			set
			{
				if ((this._nAdminLevel != value))
				{
					this.OnnAdminLevelChanging(value);
					this.SendPropertyChanging();
					this._nAdminLevel = value;
					this.SendPropertyChanged("nAdminLevel");
					this.OnnAdminLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nAuthMode", DbType="Int NOT NULL")]
		public int nAuthMode
		{
			get
			{
				return this._nAuthMode;
			}
			set
			{
				if ((this._nAuthMode != value))
				{
					this.OnnAuthModeChanging(value);
					this.SendPropertyChanging();
					this._nAuthMode = value;
					this.SendPropertyChanged("nAuthMode");
					this.OnnAuthModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nAuthLimitCount", DbType="Int NOT NULL")]
		public int nAuthLimitCount
		{
			get
			{
				return this._nAuthLimitCount;
			}
			set
			{
				if ((this._nAuthLimitCount != value))
				{
					this.OnnAuthLimitCountChanging(value);
					this.SendPropertyChanging();
					this._nAuthLimitCount = value;
					this.SendPropertyChanged("nAuthLimitCount");
					this.OnnAuthLimitCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nTimedAPB", DbType="Int NOT NULL")]
		public int nTimedAPB
		{
			get
			{
				return this._nTimedAPB;
			}
			set
			{
				if ((this._nTimedAPB != value))
				{
					this.OnnTimedAPBChanging(value);
					this.SendPropertyChanging();
					this._nTimedAPB = value;
					this.SendPropertyChanged("nTimedAPB");
					this.OnnTimedAPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nEncryption", DbType="Int NOT NULL")]
		public int nEncryption
		{
			get
			{
				return this._nEncryption;
			}
			set
			{
				if ((this._nEncryption != value))
				{
					this.OnnEncryptionChanging(value);
					this.SendPropertyChanging();
					this._nEncryption = value;
					this.SendPropertyChanged("nEncryption");
					this.OnnEncryptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_READER")]
	public partial class TB_READER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nReaderIdn;
		
		private string _sName;
		
		private int _nType;
		
		private int _nDeptIdn;
		
		private string _sIP;
		
		private string _sMacAddress;
		
		private int _nConnType;
		
		private string _sDescription;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnReaderIdnChanging(int value);
    partial void OnnReaderIdnChanged();
    partial void OnsNameChanging(string value);
    partial void OnsNameChanged();
    partial void OnnTypeChanging(int value);
    partial void OnnTypeChanged();
    partial void OnnDeptIdnChanging(int value);
    partial void OnnDeptIdnChanged();
    partial void OnsIPChanging(string value);
    partial void OnsIPChanged();
    partial void OnsMacAddressChanging(string value);
    partial void OnsMacAddressChanged();
    partial void OnnConnTypeChanging(int value);
    partial void OnnConnTypeChanged();
    partial void OnsDescriptionChanging(string value);
    partial void OnsDescriptionChanged();
    #endregion
		
		public TB_READER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nReaderIdn", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nReaderIdn
		{
			get
			{
				return this._nReaderIdn;
			}
			set
			{
				if ((this._nReaderIdn != value))
				{
					this.OnnReaderIdnChanging(value);
					this.SendPropertyChanging();
					this._nReaderIdn = value;
					this.SendPropertyChanged("nReaderIdn");
					this.OnnReaderIdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sName", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string sName
		{
			get
			{
				return this._sName;
			}
			set
			{
				if ((this._sName != value))
				{
					this.OnsNameChanging(value);
					this.SendPropertyChanging();
					this._sName = value;
					this.SendPropertyChanged("sName");
					this.OnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nType", DbType="Int NOT NULL")]
		public int nType
		{
			get
			{
				return this._nType;
			}
			set
			{
				if ((this._nType != value))
				{
					this.OnnTypeChanging(value);
					this.SendPropertyChanging();
					this._nType = value;
					this.SendPropertyChanged("nType");
					this.OnnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nDeptIdn", DbType="Int NOT NULL")]
		public int nDeptIdn
		{
			get
			{
				return this._nDeptIdn;
			}
			set
			{
				if ((this._nDeptIdn != value))
				{
					this.OnnDeptIdnChanging(value);
					this.SendPropertyChanging();
					this._nDeptIdn = value;
					this.SendPropertyChanged("nDeptIdn");
					this.OnnDeptIdnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sIP", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string sIP
		{
			get
			{
				return this._sIP;
			}
			set
			{
				if ((this._sIP != value))
				{
					this.OnsIPChanging(value);
					this.SendPropertyChanging();
					this._sIP = value;
					this.SendPropertyChanged("sIP");
					this.OnsIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMacAddress", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string sMacAddress
		{
			get
			{
				return this._sMacAddress;
			}
			set
			{
				if ((this._sMacAddress != value))
				{
					this.OnsMacAddressChanging(value);
					this.SendPropertyChanging();
					this._sMacAddress = value;
					this.SendPropertyChanged("sMacAddress");
					this.OnsMacAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nConnType", DbType="Int NOT NULL")]
		public int nConnType
		{
			get
			{
				return this._nConnType;
			}
			set
			{
				if ((this._nConnType != value))
				{
					this.OnnConnTypeChanging(value);
					this.SendPropertyChanging();
					this._nConnType = value;
					this.SendPropertyChanged("nConnType");
					this.OnnConnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDescription", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string sDescription
		{
			get
			{
				return this._sDescription;
			}
			set
			{
				if ((this._sDescription != value))
				{
					this.OnsDescriptionChanging(value);
					this.SendPropertyChanging();
					this._sDescription = value;
					this.SendPropertyChanged("sDescription");
					this.OnsDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
